name: BitCore
author: BestInTest
version: 1.0
main: pl.BestInTest.BitCore.Main
description: Plugin zabezpieczajacy serwer
commands:
  bitcore:
    description: Menu opcji pluginu.
    aliases: bit
  antyproxy:
  sprawdzip:
  2step:
  2login:
    aliases: 2l
